### PR TITLE
Look for requirements.yml or .txt relative to playbook file

### PR DESCRIPTION
**Pull request by jackrh**
First, thanks for the project! This and your blog post saved me quite a bit of time. 

The readme mentions you should place the requirements file in the same directory as your playbook, but if you follow the conventions in your example vagrant file it will never find it in the provisioning or whatever you use subfolder.

### CODE REVIEW

**Comment by geerlingguy** [comment]
This is a great idea; one question—are you sure the find command will work across at least RHEL/Debian-like distros? I don't have time to test it myself right now...)

```
find /vagrant/$PLAYBOOK_DIR -regextype posix-extended -iregex ".*/requirements.(txt|yml)
```

**Comment by jackrh** [comment]
They do, Ubuntu at least as far back as lucid, Archlinux, Cygwin, and Centos 5.

But yeah, that's a needlessly complicated find command, so the above should take care of that.

**Comment by geerlingguy** [comment]
Sorry to put this back in your court, but I think PR #14 just added a merge conflict. Should be simple enough to resolve; could you do so and then I'll finally merge this PR?

Thanks!

**Comment by jackrh** [comment]
No problem, hopefully that takes care of it

**Comment by geerlingguy** [comment]
Awesome, thanks!

**Pull request merged**
